# Generated by Django 3.0 on 2021-05-21 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dept_id',
            new_name='school_name',
        ),
    ]
