# Generated by Django 3.0 on 2021-05-22 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210521_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='school_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.School'),
            preserve_default=False,
        ),
    ]
